"""
Generate a readable HTML report from a backtest signal CSV.

Usage:
  python3 reports/generate_html_report.py reports/signals_BANKNIFTY_*.csv
  python3 reports/generate_html_report.py reports/signals_NIFTY_2026-02-01_2026-05-17.csv

Opens in any browser. Green rows = wins, red = losses.
"""
from __future__ import annotations

import argparse
import os
import sys
import glob

import pandas as pd


# ── HTML template ────────────────────────────────────────────────────────────

_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Backtest Signal Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #f5f5f5; color: #222; font-size: 14px; }
  .page { max-width: 1400px; margin: 0 auto; padding: 24px 16px; }

  /* ── Summary cards ── */
  .summary { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 28px; }
  .card {
    background: #fff; border-radius: 8px; padding: 14px 20px;
    border-left: 4px solid #999; box-shadow: 0 1px 4px rgba(0,0,0,.08);
    min-width: 150px;
  }
  .card .label { font-size: 11px; color: #888; text-transform: uppercase; letter-spacing: .5px; }
  .card .value { font-size: 22px; font-weight: 700; margin-top: 4px; }
  .card.green { border-color: #27ae60; } .card.green .value { color: #27ae60; }
  .card.red   { border-color: #e74c3c; } .card.red   .value { color: #e74c3c; }
  .card.blue  { border-color: #2980b9; } .card.blue  .value { color: #2980b9; }
  .card.gold  { border-color: #f39c12; } .card.gold  .value { color: #f39c12; }

  /* ── Section header ── */
  h1 { font-size: 22px; margin-bottom: 6px; color: #1a1a2e; }
  h2 { font-size: 14px; font-weight: 600; color: #555; margin-bottom: 16px; }
  h3 { font-size: 15px; font-weight: 700; margin: 24px 0 10px; color: #333; border-bottom: 2px solid #ddd; padding-bottom: 6px; }

  /* ── Filter bar ── */
  .filter-bar { display: flex; gap: 10px; margin-bottom: 14px; flex-wrap: wrap; align-items: center; }
  .filter-bar select, .filter-bar input {
    padding: 6px 10px; border: 1px solid #ccc; border-radius: 5px; font-size: 13px; background: #fff;
  }
  .filter-bar label { font-size: 13px; color: #555; }

  /* ── Main table ── */
  .table-wrap { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden;
          box-shadow: 0 1px 4px rgba(0,0,0,.08); }
  thead tr { background: #1a1a2e; color: #fff; }
  thead th { padding: 10px 10px; text-align: left; font-size: 12px; font-weight: 600;
             text-transform: uppercase; letter-spacing: .4px; white-space: nowrap; }
  tbody tr { border-bottom: 1px solid #f0f0f0; transition: background .1s; }
  tbody tr:hover { background: #fafafa; }
  tbody td { padding: 8px 10px; font-size: 13px; vertical-align: middle; white-space: nowrap; }

  /* row colouring */
  tr.win  { background: #f0faf4; }
  tr.loss { background: #fff5f5; }
  tr.open { background: #fffbf0; }

  /* badges */
  .badge { display: inline-block; padding: 2px 7px; border-radius: 3px; font-size: 11px; font-weight: 700; }
  .badge.call { background: #d4edda; color: #155724; }
  .badge.put  { background: #f8d7da; color: #721c24; }
  .badge.win-b  { background: #d4edda; color: #155724; }
  .badge.loss-b { background: #f8d7da; color: #721c24; }
  .badge.open-b { background: #fff3cd; color: #856404; }

  /* pnl */
  .pos { color: #27ae60; font-weight: 600; }
  .neg { color: #e74c3c; font-weight: 600; }

  /* conditions circle */
  .cond { display: inline-block; width: 22px; height: 22px; border-radius: 50%;
          background: #2980b9; color: #fff; font-size: 11px; font-weight: 700;
          text-align: center; line-height: 22px; }

  /* tooltip */
  td[title] { cursor: help; border-bottom: 1px dashed #bbb; }

  footer { margin-top: 24px; font-size: 12px; color: #aaa; text-align: center; }
</style>
</head>
<body>
<div class="page">
"""

_FOOT = """
<footer>Generated by Engine backtest report generator &bull; {source}</footer>
</div>
<script>
// ── Live filter ─────────────────────────────────────────────
function applyFilters() {
  var dir   = document.getElementById('f-dir').value.toUpperCase();
  var out   = document.getElementById('f-out').value;
  var rows  = document.querySelectorAll('#trade-table tbody tr');
  rows.forEach(function(r) {
    var show = true;
    if (dir && r.dataset.dir !== dir)     show = false;
    if (out && r.dataset.out !== out)     show = false;
    r.style.display = show ? '' : 'none';
  });
}
document.getElementById('f-dir').addEventListener('change', applyFilters);
document.getElementById('f-out').addEventListener('change', applyFilters);
</script>
</body></html>
"""


# ── Helpers ──────────────────────────────────────────────────────────────────

def _pct(v):
    try:
        f = float(v)
        cls = "pos" if f >= 0 else "neg"
        sign = "+" if f >= 0 else ""
        return f'<span class="{cls}">{sign}{f:.1f}%</span>'
    except Exception:
        return "—"


def _pnl(v):
    try:
        f = float(v)
        cls = "pos" if f >= 0 else "neg"
        sign = "+" if f >= 0 else ""
        return f'<span class="{cls}">₹{sign}{f:,.0f}</span>'
    except Exception:
        return "—"


def _price(v, decimals=2):
    try:
        return f"₹{float(v):,.{decimals}f}"
    except Exception:
        return "—"


def _fmt(v, decimals=2):
    try:
        return f"{float(v):,.{decimals}f}"
    except Exception:
        return str(v) if v is not None else "—"


def _dir_badge(d):
    cls = "call" if str(d).upper() == "CALL" else "put"
    return f'<span class="badge {cls}">{d}</span>'


def _out_badge(out, taken):
    try:
        t = int(taken)
        o = int(out)
    except Exception:
        return "—"
    if t == 0:
        return '<span class="badge open-b">SKIPPED</span>'
    if o == 1:
        return '<span class="badge win-b">WIN</span>'
    if o == 0:
        return '<span class="badge loss-b">LOSS</span>'
    return "—"


def _row_class(out, taken):
    try:
        if int(taken) == 0:
            return "open"
        return "win" if int(out) == 1 else "loss"
    except Exception:
        return ""


def _row_data(row):
    try:
        dir_attr = str(row.get("direction", "")).upper()
        out_val = str(int(row.get("outcome", -1)))
        out_map = {"1": "win", "0": "loss", "-1": "open"}
        return f'data-dir="{dir_attr}" data-out="{out_map.get(out_val, "")}"'
    except Exception:
        return ""


# ── Main builder ─────────────────────────────────────────────────────────────

def build_report(csv_paths: list[str]) -> str:
    frames = []
    for p in csv_paths:
        try:
            frames.append(pd.read_csv(p))
        except Exception as e:
            print(f"  Warning: could not read {p}: {e}", file=sys.stderr)
    if not frames:
        return "<p>No data found.</p>"

    df = pd.concat(frames, ignore_index=True)
    df = df.sort_values(["date", "time"]).reset_index(drop=True)

    # ── summary stats ──────────────────────────────────────────
    taken = df[df["trade_taken"] == 1]
    total   = len(taken)
    wins    = int((taken["outcome"] == 1).sum())
    losses  = int((taken["outcome"] == 0).sum())
    wr      = wins / total * 100 if total else 0
    total_pnl = taken["pnl"].sum() if total else 0
    avg_win  = taken[taken["outcome"] == 1]["pnl"].mean() if wins else 0
    avg_loss = taken[taken["outcome"] == 0]["pnl"].mean() if losses else 0
    pf = abs(avg_win * wins / (avg_loss * losses)) if losses and avg_loss else float("inf")
    indices = ", ".join(sorted(df["index"].unique()))
    dates   = f'{df["date"].min()} → {df["date"].max()}'

    pnl_cls = "green" if total_pnl >= 0 else "red"
    pnl_sign = "+" if total_pnl >= 0 else ""

    cards = f"""
    <div class="card blue"><div class="label">Total Signals</div><div class="value">{len(df)}</div></div>
    <div class="card blue"><div class="label">Trades Taken</div><div class="value">{total}</div></div>
    <div class="card green"><div class="label">Wins</div><div class="value">{wins}</div></div>
    <div class="card red"><div class="label">Losses</div><div class="value">{losses}</div></div>
    <div class="card gold"><div class="label">Win Rate</div><div class="value">{wr:.1f}%</div></div>
    <div class="card gold"><div class="label">Profit Factor</div><div class="value">{pf:.2f}</div></div>
    <div class="card {pnl_cls}"><div class="label">Total PnL (sim)</div><div class="value">₹{pnl_sign}{total_pnl:,.0f}</div></div>
    """

    # ── table rows ─────────────────────────────────────────────
    rows_html = []
    for i, row in df.iterrows():
        rc  = _row_class(row.get("outcome"), row.get("trade_taken"))
        rd  = _row_data(row)
        num = i + 1

        # Condition tooltip
        cond_n = row.get("conditions_met", "?")
        cond_tip = (
            f"VWAP: {'✓' if row.get('vwap_distance', 0) != 0 else '?'}  "
            f"Fib {row.get('fib_label','?')}  "
            f"RSI {_fmt(row.get('rsi'), 1)}  "
            f"PCR {_fmt(row.get('pcr'), 2)}"
        )

        fib_info = f"{row.get('fib_label','?')}% ({_fmt(row.get('fib_level'), 0)})"
        vwap_dist = row.get("vwap_distance", 0)
        vwap_cls = "pos" if float(vwap_dist or 0) >= 0 else "neg"
        vwap_sign = "+" if float(vwap_dist or 0) >= 0 else ""

        cap_before = row.get("capital_before", "")
        cap_used   = row.get("capital_used", "")
        risk_amt   = row.get("risk_amount", "")

        rows_html.append(f"""
        <tr class="{rc}" {rd}>
          <td style="color:#888;font-size:11px">{num}</td>
          <td><b>{row.get('date','')}</b></td>
          <td>{row.get('time','')}</td>
          <td><b>{row.get('index','')}</b></td>
          <td>{_dir_badge(row.get('direction',''))}</td>
          <td title="{cond_tip}"><span class="cond">{cond_n}</span></td>
          <td title="VWAP: {_fmt(row.get('vwap'),2)}">{_fmt(row.get('close'),0)}</td>
          <td title="Dist from VWAP"><span class="{vwap_cls}">{vwap_sign}{_fmt(vwap_dist, 0)}</span></td>
          <td title="Fibonacci level">{fib_info}</td>
          <td title="RSI value">{_fmt(row.get('rsi'), 1)}</td>
          <td title="Capital available before this trade">{_price(cap_before, 0) if cap_before != '' else '—'}</td>
          <td title="Total premium paid = entry price × qty" style="color:#8e44ad">{_price(cap_used, 0) if cap_used != '' else '—'}</td>
          <td title="Max loss allowed = 2% of capital" style="color:#c0392b">{_price(risk_amt, 0) if risk_amt != '' else '—'}</td>
          <td>{_price(row.get('entry_premium'))}</td>
          <td style="color:#c0392b">{_price(row.get('stop_loss'))}</td>
          <td style="color:#27ae60">{_price(row.get('target'))}</td>
          <td>{_price(row.get('exit_premium')) if row.get('trade_taken') == 1 else '—'}</td>
          <td>{_pnl(row.get('pnl')) if row.get('trade_taken') == 1 else '—'}</td>
          <td>{_pct(row.get('pnl_pct')) if row.get('trade_taken') == 1 else '—'}</td>
          <td style="font-size:12px;color:#666">{row.get('exit_reason','') if row.get('trade_taken') == 1 else 'Skipped'}</td>
          <td>{_out_badge(row.get('outcome'), row.get('trade_taken'))}</td>
        </tr>""")

    source = " + ".join(os.path.basename(p) for p in csv_paths)
    wr_bar = f'{wins} W / {losses} L'

    html = _HEAD
    html += f"""
  <h1>Backtest Signal Report</h1>
  <h2>{indices} &nbsp;|&nbsp; {dates} &nbsp;|&nbsp; {wr_bar} &nbsp;|&nbsp; Win Rate {wr:.1f}%</h2>
  <div class="summary">{cards}</div>

  <h3>All Signals & Trades</h3>

  <div class="filter-bar">
    <label>Filter by Direction:</label>
    <select id="f-dir">
      <option value="">All</option>
      <option value="CALL">CALL only</option>
      <option value="PUT">PUT only</option>
    </select>
    <label>Filter by Outcome:</label>
    <select id="f-out">
      <option value="">All</option>
      <option value="win">Wins</option>
      <option value="loss">Losses</option>
      <option value="open">Skipped</option>
    </select>
  </div>

  <div class="table-wrap">
  <table id="trade-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Date</th>
        <th>Time</th>
        <th>Index</th>
        <th>Direction</th>
        <th title="Number of conditions met (hover for detail)">Conds</th>
        <th>Close</th>
        <th title="Close minus VWAP — positive means price is above VWAP">VWAP Dist</th>
        <th title="Fibonacci level price was near">Fib Level</th>
        <th title="RSI value at signal time">RSI</th>
        <th title="Your account balance before this trade was placed">Capital Before</th>
        <th title="Total premium paid = entry price × quantity">Capital Used</th>
        <th title="Maximum loss allowed on this trade = 2% of capital">Max Risk</th>
        <th>Entry Premium</th>
        <th>Stop Loss</th>
        <th title="2.5× target">Target</th>
        <th>Exit Premium</th>
        <th>P&amp;L (₹)</th>
        <th>P&amp;L %</th>
        <th>Exit Reason</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows_html)}
    </tbody>
  </table>
  </div>
"""
    html += _FOOT.replace("{source}", source)
    return html


# ── CLI ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate an HTML report from backtest signal CSVs"
    )
    parser.add_argument(
        "csv", nargs="+",
        help="Path(s) to signal CSV files. Supports wildcards.",
    )
    parser.add_argument(
        "--out", "-o", default=None,
        help="Output HTML file path (default: same folder as first CSV with .html extension)",
    )
    args = parser.parse_args()

    paths: list[str] = []
    for pattern in args.csv:
        expanded = glob.glob(pattern)
        if not expanded:
            print(f"Warning: no files matched: {pattern}", file=sys.stderr)
        paths.extend(expanded)

    if not paths:
        print("No CSV files found.", file=sys.stderr)
        sys.exit(1)

    html = build_report(paths)

    if args.out:
        out_path = args.out
    else:
        first = paths[0]
        base  = os.path.splitext(first)[0]
        if len(paths) > 1:
            # combined report — place in reports/ directory
            folder = os.path.dirname(first)
            out_path = os.path.join(folder, "backtest_report.html")
        else:
            out_path = base + ".html"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\nReport saved → {out_path}")
    print(f"Open in browser: xdg-open \"{out_path}\"")


if __name__ == "__main__":
    main()
